version: '2' 
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_PASSWORD=password123!
      - DB_HOST=patate
      - DB_USER=wordpress
      - DB_NAME=wordpress
  db:
    image: mysql:8.0.0
    volumes:
      - /tmp/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password123!
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password123!
