apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: albourguignon/cr460-wp
        ports:
        - containerPort: 80
        env:
          - name: DB_PASSWORD
            value: "w2preswsw"
          - name: DB_HOST
            value: "35.203.9.14"
          - name: DB_USER
            value: "wordpress"
          - name: DB_NAME
            value: "wordpress"
