apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: rlabelle02/cr460
        ports:
        - containerPort: 80
        env:
          - name: DB_PASSWORD
            value: "w2preswsw"
          - name: DB_HOST
            value: "35.203.70.28"
          - name: DB_USER
            value: "wordpress"
          - name: DB_NAME
            value: "wordpress"
