apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: wp-service
          servicePort: 80
      - path: /web2
        backend:
            serviceName: wp-service
            servicePort: 80
