apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /web
        backend:
          serviceName: wp-service
          servicePort: 80
